fromRJSON <- function(x, ...) {
  return(jsonlite::fromJSON(sprintf(x, ...),
    simplifyVector = FALSE,
    simplifyDataFrame = FALSE,
    simplifyMatrix = FALSE
  ))
}

handle_err_result <- function(res) {
  if (res$type == "error") {
    return(TRUE)
  }
  return(FALSE)
}

make_id_provider <- function(next_id = 0) {
  function()
    next_id <<- next_id + 1
}
get_new_id <- make_id_provider()

#' Generates a token for a given file or content
#'
#' Note that either `filepath` or `content` must be provided, but never both.
#' The token is then generated by hashing the file's content or the provided content,
#' depending on what was provided.
#'
#' @param filepath Path to a file
#' @param content Arbitrary content
#' @return The token
get_filetoken <- function(filepath = rlang::missing_arg(), content = rlang::missing_arg()) {
  if (!rlang::is_missing(filepath)) {
    stopifnot(is.character(filepath), file.exists(filepath))
    token <- digest::digest(readLines(filepath))
  } else if (!rlang::is_missing(content)) {
    stopifnot(is.character(content))
    token <- digest::digest(content)
  } else {
    stop("Either filepath or content must be provided")
  }
  return(token)
}
