make_id_provider <- function(next_id = 0) {
  function() {
    next_id <<- next_id + 1
    return(as.character(next_id))
  }
}
get_new_id <- make_id_provider()

#' Generates a token for a given file or content
#'
#' Note that either `filepath` or `content` must be provided, but never both.
#' The token is then generated by hashing the file's content or the provided content,
#' depending on what was provided.
#'
#' @param filepath Path to a file
#' @param content Arbitrary content
#' @return The token
get_filetoken <- function(filepath = rlang::missing_arg(), content = rlang::missing_arg()) {
  if (!rlang::is_missing(filepath)) {
    stopifnot(is.character(filepath) || is.vector(filepath))
    # sort to ensure that a different order will result in the same token
    filepath <- sort(lapply(c(filepath), normalizePath) |> unlist())
    stopifnot(file.exists(filepath))
    token <- digest::digest(lapply(filepath, readLines))
  } else if (!rlang::is_missing(content)) {
    stopifnot(is.character(content))
    token <- digest::digest(content)
  } else {
    stop("Either filepath or content must be provided")
  }
  return(token)
}

#' Checks if the given response was successful or not.
#'
#' The function always returns a list with the response's ID. In case of an
#' error, the list also contains the errors reason. In case of a successful
#' response, the list also contains the complete response.
#'
#' @param res The response to handle
#'
#' @return A list with either the error's reason or the complete response
#' \describe{
#'   \item{id}{The ID of the response (only in case of success).}
#'   \item{res}{The complete response object (only in case of success).}
#' }
#' or
#' \describe{
#'   \item{error}{The reason for the error (only present in case of an error).}
#' }
#'
#' @seealso [send_request()]
handle_response <- function(res) {
  if (res$type == "error") {
    return(list(error = res$reason))
  }
  return(list(id = res$id, res = res))
}

#' Send the given request over the given connection and handle a possible error
#'
#' @param con The connection to use
#' @param request The request to send
#'
#' @return See [handle_response()] for possible return values
send_request_handle_response <- function(con, request) {
  res <- send_request(con, request)
  return(handle_response(res))
}
